name: 'slack-notify'

inputs:
  status:
    required: true
  event_name:
    required: true
  slack_incoming_url:
    required: true

runs:
  using: 'composite'

  steps:
    - name: Set Report Result
      if: ${{ always() }}
      run: |
        if [ ${{ inputs.status }} = 'success' ]
        then      
          echo "result=:large_green_circle:" >> $GITHUB_ENV
        else
          echo "result=:red_circle:" >> $GITHUB_ENV
        fi
      
    - name: Set Report Title
      if: ${{ always() }}
      run: |
        if [ ${{ inputs.event_name }} = 'push' ]
        then
          echo "title=Main 브랜치 Push" >> $GITHUB_ENV
        elif [ ${{ inputs.event_name }} = 'pull_request' ]
        then
          echo "title=#${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}" >> $GITHUB_ENV
        fi
        
    - name: Get Time
      if: ${{ always() }}
      id: time
      uses: nanzm/get-time-action@v1.1
      with:
        timeZone: 9
        format: 'YYYY-MM-DD HH:mm:ss'
        
    - name: Notify To Slack
      if: ${{ always() }}
      id: slack
      uses: slackapi/slack-github-action@v1.18.0
      with:
        payload: |
          {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ":rocket: *${{ env.title }}*"
                }
              },
              {
                "type": "divider"
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*날짜 :* ${{ steps.time.outputs.time }}"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*결과 :* ${{ env.result }}"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*PR 링크 :* ${{ github.event.pull_request.html_url }}"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.slack_incoming_url }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
