name: 'slack-notify'

inputs:
  slack_webhook_url:
    required: true

runs:
  using: 'composite'

  steps:
    - name: Set Report Result
      shell: bash
      run: |
        if [ ${{ job.status }} = 'success' ]
        then      
          echo "result=:large_green_circle:" >> $GITHUB_ENV
        else
          echo "result=:red_circle:" >> $GITHUB_ENV
        fi
      
    - name: Set Report Title And Link
      shell: bash
      run: |
        if [ ${{ github.event_name }} = 'push' ]
        then
          echo "title=${GITHUB_REF#refs/heads/} 브랜치 Push" >> $GITHUB_ENV
          echo "link=https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}" >> $GITHUB_ENV
        elif [ ${{ github.event_name }} = 'pull_request' ]
        then
          echo "title=#${{ github.event.pull_request.number}} PR 생성" >> $GITHUB_ENV
          echo "link=${{ github.event.pull_request.html_url }}" >> $GITHUB_ENV
        fi
        echo "actions_link=https://github.com/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}/checks" >> $GITHUB_ENV
        
    - name: Get Time
      id: time
      uses: nanzm/get-time-action@v1.1
      with:
        timeZone: 9
        format: 'YYYY-MM-DD HH:mm:ss'
        
    - name: Notify To Slack
      id: slack
      uses: slackapi/slack-github-action@v1.18.0
      with:
        payload: |
          {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ":rocket: *${{ env.title }}*"
                }
              },
              {
                "type": "divider"
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*날짜 :* ${{ steps.time.outputs.time }}"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*작성자 :* ${{ github.event.pull_request.sender.login }}"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*결과 :* ${{ env.result }}"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "*Actions 링크 :* ${{ env.actions_link }}"
                }
              },
              {
                "type": "section",
                "text": {
                   "type": "mrkdwn",
                   "text": "*PR 및 커밋 링크 :* ${{ env.link }}"
                }
              }
            ]
          }
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.slack_webhook_url }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
