# This is a basic workflow to help you get started with Actions

name: CI


on:
  push:
    branches: [ "main" ]
    
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 8
          format: 'YYYY-MM-DD HH:mm:ss'

      - name: Set Success Result
        if: ${{ success() }}
        run: echo "result=:large_green_circle:" >> $GITHUB_ENV
        
      - name: Set Fail Result
        if: ${{ failure() }}
        run: echo "result=:large_red_circle:" >> $GITHUB_ENV
        
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "context",
                  "elements": [
                    {
                      "type": "image",
                      "image_url": "https://github.githubassets.com/images/mona-loading-default.gif",
                      "alt_text": "cute cat"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*CI 피드백 리포트*"
                    }
                  ]
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*날짜 :* ${{ steps.time.outputs.time }}"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*결과 :* ${{ env.result }}"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*링크 :* ${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
                  }
                },
                {
                  "type": "divider"
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        
